parameters:
#    hectoritoh_apps_planner.example.class: Hectoritoh\Apps\PlannerBundle\Example

services:
#    hectoritoh_apps_planner.example:
#        class: %hectoritoh_apps_planner.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
