Hectoritoh\Apps\PlannerBundle\Entity\Documento:
    type: entity
    table: documento
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 250
            fixed: false
            nullable: false
        detalle:
            type: text
            length: 250
            nullable: true
        url:
            type: datetime
            nullable: false
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false


    lifecycleCallbacks:
        prePersist: [preInsert]
        preUpdate: [preUpdate]
